<h1> Numpy </h1>  (for jupyter: ! pip install numpy)
<h3>  - Handling Arrays </h3>


In [43]:
import numpy as np
a= np.array([1,2,3,4])
b=np.array([[1,2,3],[5,6,7,8]])
print(a.itemsize) 
print(b.itemsize)


4
8


In [44]:
np.empty((3,4),dtype='int8')

array([[ 16,  17, -32, -54],
       [ 96,   1,   0,   0],
       [-29,   2,   0,   0]], dtype=int8)

In [45]:
np.zeros((3,4),dtype='int8')  # array with 0's

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [47]:
np.ones((3,4),dtype='int8')  #array with 1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [48]:
np.full((2,4),7)  # array with same value

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [49]:
np.eye(3)  #Creates a 2-D array with ones on the diagonal and zeros elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h3> Class Code Below </h3>

In [89]:
list_arr = [[3,4,2,4],[3,5,2,4]]

In [90]:
arr = np.array(list_arr)

In [91]:
print(list_arr)

[[3, 4, 2, 4], [3, 5, 2, 4]]


In [92]:
print(arr)

[[3 4 2 4]
 [3 5 2 4]]


In [93]:
type(arr)

numpy.ndarray

In [99]:
print(arr.shape)  # structure of array how many rows , columns
print(arr.dtype)  # dataype of array
print(arr.itemsize) # byte size for everyelement being stored  like int takes 4 bytes
print(arr.size)  # how many elements rows x col
print(arr.ndim) # no. of dimension


(2, 4)
int32
4
8
2


In [107]:
a = np.arange(24)
b = a.reshape(3,4,2)
print(a)
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
3


<h3> Creating with Numerical Ranges </h3>

In [129]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [130]:
print(np.logspace(0,2,100))

[  1.           1.04761575   1.09749877   1.149757     1.20450354
   1.26185688   1.32194115   1.38488637   1.45082878   1.51991108
   1.59228279   1.66810054   1.7475284    1.83073828   1.91791026
   2.009233     2.10490414   2.20513074   2.3101297    2.42012826
   2.53536449   2.65608778   2.7825594    2.91505306   3.05385551
   3.19926714   3.35160265   3.51119173   3.67837977   3.85352859
   4.03701726   4.22924287   4.43062146   4.64158883   4.86260158
   5.09413801   5.33669923   5.59081018   5.85702082   6.13590727
   6.42807312   6.73415066   7.05480231   7.39072203   7.74263683
   8.11130831   8.49753436   8.90215085   9.32603347   9.77009957
  10.23531022  10.72267222  11.23324033  11.76811952  12.32846739
  12.91549665  13.53047775  14.17474163  14.84968262  15.55676144
  16.29750835  17.07352647  17.88649529  18.73817423  19.6304065
  20.56512308  21.5443469   22.5701972   23.64489413  24.77076356
  25.95024211  27.18588243  28.48035868  29.8364724   31.2571585
  32.7454916

<h3> Indexing </h3>

In [133]:
arr2 = np.arange(84)

In [134]:
arr2 = arr2.reshape((3,4,7))

In [138]:

print(arr2)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]
  [42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55]]

 [[56 57 58 59 60 61 62]
  [63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76]
  [77 78 79 80 81 82 83]]]


In [140]:
arr2[0,:,2:4] #month1 all week wed and thursday

array([[ 2,  3],
       [ 9, 10],
       [16, 17],
       [23, 24]])

In [145]:
arr2[0:1,:,[1,3]] #month1 all week tue and thursday

array([[[ 1,  3],
        [ 8, 10],
        [15, 17],
        [22, 24]]])

<h3> Boolean Indexing </h3>

In [146]:
arr2[arr2>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83])

<h3> Vectorization </h3>

In [149]:
a= np.array([[4,5],[5,4]])
b= np.array([[5,2],[1,8]])

In [152]:
np.min(arr2, axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [153]:
np.max(arr2, axis=0)

array([[56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83]])

In [155]:
np.min(arr2,axis=1)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [28, 29, 30, 31, 32, 33, 34],
       [56, 57, 58, 59, 60, 61, 62]])

In [157]:
np.max(arr2, axis=1)

array([[21, 22, 23, 24, 25, 26, 27],
       [49, 50, 51, 52, 53, 54, 55],
       [77, 78, 79, 80, 81, 82, 83]])

In [158]:
np.max(arr2 , axis=2)  # depends on shape arr2.shape

array([[ 6, 13, 20, 27],
       [34, 41, 48, 55],
       [62, 69, 76, 83]])